workflows:
  android:
    name: build, test & publish Android version
    scripts:
      - ...
  ios:
    name: build, test & publish iOS version
    scripts:
      - ...
  my-workflow:
    environment:
      flutter: master
